<a href="https://colab.research.google.com/github/rajkumar-11812510/Rajkumar-Muraoo/blob/main/Numpy_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy Operations:
* Array with Array
* Array with Scalars
* Universal Array Functions

In [1]:
import numpy as np

In [2]:
arr=np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
# Addition of array
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [6]:
# Subtraction of array'
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
# Multiplication of array
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [8]:
# Division of array gives nan for array/0 and other gives proper result
arr/arr

/tmp/ipython-input-312236344.py:2: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [9]:
# Power of arr
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [13]:
# Finding Squareroot
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [14]:
# Exponential
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [15]:
# maximum
np.max(arr)

np.int64(10)