<a href="https://colab.research.google.com/github/rajkumar-11812510/Rajkumar-Muraoo/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
my_list=[1,2,3]


In [2]:
import numpy as np


In [4]:
arr=np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Find array number betwwen these

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [16]:
np.zeros((6,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
np.ones(4)


array([1., 1., 1., 1.])

In [18]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

np.linspace is a function in NumPy used to create evenly spaced numbers over a specified interval.

One dimension has 1 bracket []
2 dimension= [[]]
3 dimesion =[[[]]]

In [19]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

Identity Matrrix

In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
np.random.rand(5)

array([0.86642642, 0.25566725, 0.01151994, 0.33034363, 0.25554985])

In [22]:
np.random.randn(4)

array([-0.95609214, -0.75221911,  0.59249231,  0.52013108])

In [23]:
np.random.randn(2,2)

array([[ 1.17171978, -1.71975507],
       [-0.02863088, -0.06598406]])

In [25]:
np.random.randint(2,99)

4

Comparision of random ns arr

In [27]:
arr=np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
ranarr=np.random.randint(0,50,10)
ranarr

array([ 0, 38, 11, 14, 30, 32,  9, 26, 22,  9])

In [31]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

Find Max and min values in array

In [32]:
ranarr.max()

np.int64(38)

In [33]:
ranarr.min()

np.int64(0)

In [34]:
ranarr

array([ 0, 38, 11, 14, 30, 32,  9, 26, 22,  9])

In [38]:
print(ranarr.argmax())

1


In [39]:
print(ranarr.argmin())

0
